#!/usr/local/bin/fish

# $argv[1] $argv[2]

if [ (count $argv) -lt 2 ]
  echo "Specify arguments. 'npr {NEXT_BRANCH_NAME} {LAST_BRANCH_NAME}'"
  exit
end

set NEXT_BRANCH_NAME $argv[1]
set TARGET_BASE_NAME $argv[2]

set LAST_BRANCH_NAME (git rev-parse --abbrev-ref @)
echo "last branch: [ $LAST_BRANCH_NAME ]"

git fetch --all
git checkout $TARGET_BASE_NAME
git pull

switch $LAST_BRANCH_NAME
  case master 'deployment/*' 'release/*'
    echo "Skip delete: target is $LAST_BRANCH_NAME"
  case '*'
    echo "Delete branch: $LAST_BRANCH_NAME"
    git branch -D $LAST_BRANCH_NAME
end

git checkout -b $NEXT_BRANCH_NAME
git commit --allow-empty -m "NOPR: squash me [ci skip]"
git push -f -u
hub pull-request  -b $TARGET_BASE_NAME
