#!/usr/local/bin/fish

function help_exit
  echo 'Usage: [options] arguments...'
  echo 'Options:'
  echo '-c : Input manual commit comment'
  echo 'Arguments: '
  echo '-n : Next Branch'
  echo '-b : Base Branch'
  exit 1
end

if [ (count $argv) -lt 3 ]
  help_exit
end

set argv $argv --

set i 1
while true
  switch $argv[$i]
    case -c
      echo 'option -c is specified'
      set MANUAL_COMMIT_COMMENT true
    case -n
      set i (math $i + 1)
      echo "value of -n is" $argv[$i]
      set NEXT_BRANCH_NAME $argv[$i]
    case -b
      set i (math $i + 1)
      echo "value of -b is" $argv[$i]
      set BASE_BRANCH_NAME $argv[$i]
    case --
      break
  end
  set i (math $i + 1)
end

if [ $NEXT_BRANCH_NAME -a $BASE_BRANCH_NAME ]
  echo 'Every arguments are specified'
else
  echo 'Arguments are not valid'
  exit
end

set LAST_BRANCH_NAME (git rev-parse --abbrev-ref @)
echo "last branch: [ $LAST_BRANCH_NAME ]"

git fetch --all
git checkout $BASE_BRANCH_NAME
git pull origin $BASE_BRANCH_NAME

switch $LAST_BRANCH_NAME
  case master 'deployment/*' 'release/*' 'release-*'
    echo "Skip delete: target is $LAST_BRANCH_NAME"
  case '*'
    echo "Delete branch: $LAST_BRANCH_NAME"
    git branch -D $LAST_BRANCH_NAME
end

git checkout -b $NEXT_BRANCH_NAME

if [ $MANUAL_COMMIT_COMMENT ]
  git commit --allow-empty
else
  git commit --allow-empty -m "NOPR: squash me [ci skip]"
end

git push -f -u

hub pull-request -b $BASE_BRANCH_NAME
